#Type  Name     ID  GECOS                                      Home Dir
g      dnf-p2p  -   -                                          -
u      dnf-p2p  -   "System user for DNF P2P Package Sharing"  /var/cache/dnf-plugin-p2p
